--- #YAML:1.0
name:               Set-IntSpan-Fast-XS
version:            0.05
abstract:           Faster Set::IntSpan::Fast
author:
    - Andy Armstrong <andy@hexten.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Swap:          0.07
    List::Util:          0
    Set::IntSpan::Fast:  1.13
    Test::More:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
